-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.acte (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  collectivite_id uuid NOT NULL,
  type_acte USER-DEFINED NOT NULL,
  numero_interne text,
  numero_actes text,
  objet_court text NOT NULL,
  objet_complet text,
  date_acte date NOT NULL,
  date_seance date,
  organe text,
  rapporteur text,
  exec_declared boolean NOT NULL DEFAULT false,
  exec_declared_date date,
  exec_confirmed boolean NOT NULL DEFAULT false,
  exec_confirmed_date date,
  exec_proof_id uuid,
  version integer NOT NULL DEFAULT 1 CHECK (version > 0),
  valid_from timestamp with time zone NOT NULL DEFAULT now(),
  valid_to timestamp with time zone,
  supersedes_id uuid,
  metadata jsonb NOT NULL DEFAULT '{"schemaVersion": 1}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  CONSTRAINT acte_pkey PRIMARY KEY (id),
  CONSTRAINT acte_collectivite_id_fkey FOREIGN KEY (collectivite_id) REFERENCES public.collectivite(id),
  CONSTRAINT acte_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT acte_exec_proof_fkey FOREIGN KEY (exec_proof_id) REFERENCES public.proof(id),
  CONSTRAINT acte_supersedes_id_fkey FOREIGN KEY (supersedes_id) REFERENCES public.acte(id)
);
CREATE TABLE public.cafe_reflection_tasks (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  session_id uuid,
  conversation_id uuid,
  trigger_utterance_id uuid,
  trigger_participant_id uuid,
  question_text text,
  context_snapshot jsonb,
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'running'::text, 'done'::text, 'failed'::text])),
  result_summary text,
  result_full text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT cafe_reflection_tasks_pkey PRIMARY KEY (id)
);
CREATE TABLE public.charter_signatures (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  lead_id uuid NOT NULL,
  signer_name text NOT NULL,
  signer_email text NOT NULL,
  signer_role text,
  organization_name text,
  commune_name text NOT NULL,
  charter_version text DEFAULT '1.0'::text,
  charter_hash text,
  commitments jsonb DEFAULT '[]'::jsonb,
  ip_address inet,
  user_agent text,
  signed_at timestamp with time zone DEFAULT now(),
  verified boolean DEFAULT false,
  verified_at timestamp with time zone,
  verified_by uuid,
  CONSTRAINT charter_signatures_pkey PRIMARY KEY (id),
  CONSTRAINT charter_signatures_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES public.transparency_leads(id),
  CONSTRAINT charter_signatures_verified_by_fkey FOREIGN KEY (verified_by) REFERENCES auth.users(id)
);
CREATE TABLE public.chat_interactions (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  user_id uuid,
  question text NOT NULL,
  answer text,
  sources jsonb,
  metadata jsonb DEFAULT '{}'::jsonb,
  feedback text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT chat_interactions_pkey PRIMARY KEY (id),
  CONSTRAINT chat_interactions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.chatbot_settings (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  welcome_message text DEFAULT 'Bonjour ! Comment puis-je vous aider concernant la vie locale à Corte ?'::text,
  fallback_message text DEFAULT 'Désolé, je ne trouve pas de réponse. Souhaitez-vous créer une proposition ?'::text,
  similarity_threshold double precision DEFAULT 0.65,
  max_sources integer DEFAULT 3,
  enable_proposition_creation boolean DEFAULT true,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  metadata jsonb DEFAULT '{"schemaVersion": 1}'::jsonb,
  CONSTRAINT chatbot_settings_pkey PRIMARY KEY (id)
);
CREATE TABLE public.civic_audit_log (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  actor_type USER-DEFINED NOT NULL DEFAULT 'HUMAIN'::civic_actor_type,
  action USER-DEFINED NOT NULL,
  entity_type USER-DEFINED NOT NULL,
  entity_id uuid NOT NULL,
  payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  ip_address inet,
  user_agent text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT civic_audit_log_pkey PRIMARY KEY (id),
  CONSTRAINT civic_audit_log_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.civic_rag_document (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  source_type USER-DEFINED NOT NULL,
  source_id uuid,
  collectivite_id uuid,
  title text NOT NULL,
  content text NOT NULL,
  summary text,
  index_type USER-DEFINED NOT NULL DEFAULT 'PROBATOIRE'::rag_index_type,
  domain text,
  keywords ARRAY,
  metadata jsonb NOT NULL DEFAULT '{"schemaVersion": 1}'::jsonb,
  embedding USER-DEFINED,
  is_current boolean NOT NULL DEFAULT true,
  version integer NOT NULL DEFAULT 1,
  supersedes_id uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT civic_rag_document_pkey PRIMARY KEY (id),
  CONSTRAINT civic_rag_document_collectivite_id_fkey FOREIGN KEY (collectivite_id) REFERENCES public.collectivite(id),
  CONSTRAINT civic_rag_document_supersedes_id_fkey FOREIGN KEY (supersedes_id) REFERENCES public.civic_rag_document(id)
);
CREATE TABLE public.civic_stats_snapshot (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  collectivite_id uuid NOT NULL,
  snapshot_date date NOT NULL,
  snapshot_type text NOT NULL CHECK (snapshot_type = ANY (ARRAY['MONTHLY'::text, 'QUARTERLY'::text, 'YEARLY'::text])),
  total_actes integer NOT NULL DEFAULT 0,
  transmis_confirmes integer NOT NULL DEFAULT 0,
  taux_transmission numeric,
  delai_moyen_transmission integer,
  total_demandes integer NOT NULL DEFAULT 0,
  demandes_repondues integer NOT NULL DEFAULT 0,
  refus_implicites integer NOT NULL DEFAULT 0,
  taux_reponse numeric,
  delai_moyen_reponse integer,
  total_recours integer NOT NULL DEFAULT 0,
  recours_favorables integer NOT NULL DEFAULT 0,
  taux_succes_recours numeric,
  score_transparence numeric,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT civic_stats_snapshot_pkey PRIMARY KEY (id),
  CONSTRAINT civic_stats_snapshot_collectivite_id_fkey FOREIGN KEY (collectivite_id) REFERENCES public.collectivite(id)
);
CREATE TABLE public.civic_user_profile (
  id uuid NOT NULL,
  display_name text NOT NULL DEFAULT ''::text,
  role USER-DEFINED NOT NULL DEFAULT 'CITIZEN_REVIEWER'::civic_user_role,
  organisation USER-DEFINED NOT NULL DEFAULT 'CITOYEN'::civic_organisation,
  organisation_name text,
  collectivite_id uuid,
  email_notifications boolean NOT NULL DEFAULT false,
  metadata jsonb NOT NULL DEFAULT '{"schemaVersion": 1}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT civic_user_profile_pkey PRIMARY KEY (id),
  CONSTRAINT civic_user_profile_collectivite_fkey FOREIGN KEY (collectivite_id) REFERENCES public.collectivite(id),
  CONSTRAINT civic_user_profile_id_fkey FOREIGN KEY (id) REFERENCES public.users(id)
);
CREATE TABLE public.collected_data (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  source_url text NOT NULL,
  data_type text NOT NULL CHECK (data_type = ANY (ARRAY['Titre'::text, 'Description'::text, 'Date'::text, 'Lieu'::text, 'Personne'::text, 'Organisation'::text, 'Autre'::text])),
  value text NOT NULL,
  status text NOT NULL DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'reviewed'::text, 'published'::text, 'archived'::text])),
  metadata jsonb DEFAULT '{"schemaVersion": 1}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT collected_data_pkey PRIMARY KEY (id),
  CONSTRAINT collected_data_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.collectivite (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  type USER-DEFINED NOT NULL DEFAULT 'COMMUNE'::collectivite_type,
  code_insee text NOT NULL UNIQUE,
  nom_officiel text NOT NULL,
  nom_courant text,
  departement text NOT NULL,
  region text NOT NULL,
  siren text UNIQUE,
  site_web text,
  email_contact text,
  date_activation_systeme date,
  population integer CHECK (population IS NULL OR population >= 0),
  metadata jsonb NOT NULL DEFAULT '{"schemaVersion": 1}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT collectivite_pkey PRIMARY KEY (id)
);
CREATE TABLE public.comments (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  post_id uuid NOT NULL,
  user_id uuid NOT NULL,
  content text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  metadata jsonb NOT NULL DEFAULT '{"schemaVersion": 1}'::jsonb,
  CONSTRAINT comments_pkey PRIMARY KEY (id),
  CONSTRAINT comments_post_id_fkey FOREIGN KEY (post_id) REFERENCES public.posts(id),
  CONSTRAINT comments_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.consent_audit_log (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  consent_type text NOT NULL,
  previous_value boolean,
  new_value boolean NOT NULL,
  change_reason text,
  consent_version text NOT NULL,
  source text NOT NULL,
  changed_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT consent_audit_log_pkey PRIMARY KEY (id),
  CONSTRAINT consent_audit_log_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.consultation_imports (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  local_consultation_id uuid NOT NULL,
  source_instance text NOT NULL,
  source_consultation_id uuid NOT NULL,
  source_slug text NOT NULL,
  imported_at timestamp with time zone NOT NULL DEFAULT now(),
  imported_by uuid,
  auto_sync boolean NOT NULL DEFAULT true,
  sync_interval_hours integer DEFAULT 1,
  status text NOT NULL DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'paused'::text, 'revoked'::text])),
  last_check_at timestamp with time zone,
  CONSTRAINT consultation_imports_pkey PRIMARY KEY (id),
  CONSTRAINT consultation_imports_local_fkey FOREIGN KEY (local_consultation_id) REFERENCES public.consultations(id)
);
CREATE TABLE public.consultation_responses (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  consultation_id uuid NOT NULL,
  user_id uuid,
  session_id text,
  responses jsonb NOT NULL DEFAULT '{}'::jsonb,
  schema_version integer NOT NULL DEFAULT 1,
  is_complete boolean NOT NULL DEFAULT false,
  ip_hash text,
  user_agent_category text,
  source text DEFAULT 'web'::text,
  started_at timestamp with time zone DEFAULT now(),
  completed_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  sync_status text DEFAULT 'pending'::text CHECK (sync_status = ANY (ARRAY['pending'::text, 'synced'::text, 'failed'::text, 'not_applicable'::text])),
  synced_at timestamp with time zone,
  source_response_id uuid,
  sync_attempts integer NOT NULL DEFAULT 0,
  sync_error text,
  CONSTRAINT consultation_responses_pkey PRIMARY KEY (id),
  CONSTRAINT consultation_responses_consultation_id_fkey FOREIGN KEY (consultation_id) REFERENCES public.consultations(id)
);
CREATE TABLE public.consultations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  slug text NOT NULL UNIQUE,
  title text NOT NULL,
  description text,
  starts_at timestamp with time zone DEFAULT now(),
  ends_at timestamp with time zone,
  schema jsonb NOT NULL DEFAULT '{}'::jsonb,
  response_count integer NOT NULL DEFAULT 0,
  status text NOT NULL DEFAULT 'active'::text CHECK (status = ANY (ARRAY['draft'::text, 'active'::text, 'closed'::text, 'archived'::text])),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  scope text NOT NULL DEFAULT 'local'::text CHECK (scope = ANY (ARRAY['local'::text, 'regional'::text, 'national'::text, 'custom'::text])),
  source_instance text,
  source_consultation_id uuid,
  sync_endpoint text,
  sync_api_key text,
  federation_config jsonb DEFAULT '{}'::jsonb,
  last_synced_at timestamp with time zone,
  synced_response_count integer NOT NULL DEFAULT 0,
  petition_local text,
  petition_regional text,
  petition_national text,
  petitions_metadata jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT consultations_pkey PRIMARY KEY (id)
);
CREATE TABLE public.content_subscriptions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  content_type text NOT NULL CHECK (content_type = ANY (ARRAY['post'::text, 'proposition'::text, 'wiki_page'::text])),
  content_id uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT content_subscriptions_pkey PRIMARY KEY (id),
  CONSTRAINT content_subscriptions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.cop_agent_identities (
  agent_id uuid NOT NULL DEFAULT gen_random_uuid(),
  agent_name text NOT NULL,
  agent_class text NOT NULL,
  description text,
  owner_human_id uuid,
  owner_group_id uuid,
  operator_id uuid,
  domains jsonb NOT NULL DEFAULT '[]'::jsonb,
  permissions jsonb NOT NULL DEFAULT '{}'::jsonb,
  constraints jsonb NOT NULL DEFAULT '{}'::jsonb,
  issued_by text,
  valid_until timestamp with time zone,
  profile jsonb NOT NULL DEFAULT '{}'::jsonb,
  status text NOT NULL DEFAULT 'active'::text,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT cop_agent_identities_pkey PRIMARY KEY (agent_id)
);
CREATE TABLE public.cop_agents (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  network_id text NOT NULL,
  node_id text NOT NULL,
  instance_id text NOT NULL,
  agent_name text NOT NULL,
  handler_type text NOT NULL DEFAULT 'runtime'::text,
  handler_path text,
  intents jsonb NOT NULL DEFAULT '[]'::jsonb,
  active boolean NOT NULL DEFAULT true,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT cop_agents_pkey PRIMARY KEY (id)
);
CREATE TABLE public.cop_artifact (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  topic_id uuid NOT NULL,
  source_job_id uuid,
  source_step_id uuid,
  type text NOT NULL,
  format text,
  payload jsonb DEFAULT '{}'::jsonb,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT cop_artifact_pkey PRIMARY KEY (id),
  CONSTRAINT cop_artifact_source_job_id_fkey FOREIGN KEY (source_job_id) REFERENCES public.cop_job(id),
  CONSTRAINT cop_artifact_source_step_id_fkey FOREIGN KEY (source_step_id) REFERENCES public.cop_step(id),
  CONSTRAINT cop_artifact_topic_id_fkey FOREIGN KEY (topic_id) REFERENCES public.cop_topic(id)
);
CREATE TABLE public.cop_artifacts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  correlation_id uuid,
  message_id uuid,
  event_id uuid,
  network_id text,
  node_id text,
  instance_id text,
  agent_name text,
  artifact_type text NOT NULL,
  artifact_kind text NOT NULL,
  content jsonb NOT NULL,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT cop_artifacts_pkey PRIMARY KEY (id)
);
CREATE TABLE public.cop_debug_logs (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  correlation_id uuid,
  message_id uuid,
  event_id uuid,
  location text NOT NULL,
  stage text NOT NULL,
  direction text,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT cop_debug_logs_pkey PRIMARY KEY (id)
);
CREATE TABLE public.cop_event (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  topic_id uuid NOT NULL,
  type text NOT NULL,
  payload jsonb DEFAULT '{}'::jsonb,
  meta jsonb DEFAULT '{}'::jsonb,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT cop_event_pkey PRIMARY KEY (id),
  CONSTRAINT cop_event_topic_id_fkey FOREIGN KEY (topic_id) REFERENCES public.cop_topic(id)
);
CREATE TABLE public.cop_events (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  cop_version text NOT NULL,
  event_id uuid NOT NULL,
  correlation_id uuid,
  from_addr text NOT NULL,
  channel text NOT NULL,
  event_type text NOT NULL,
  payload jsonb NOT NULL,
  metadata jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT cop_events_pkey PRIMARY KEY (id)
);
CREATE TABLE public.cop_job (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  topic_id uuid NOT NULL,
  type text NOT NULL,
  status text NOT NULL DEFAULT 'pending'::text,
  attempts integer NOT NULL DEFAULT 0,
  max_attempts integer NOT NULL DEFAULT 3,
  worker_id text,
  lease_expires_at timestamp with time zone,
  last_error text,
  meta jsonb DEFAULT '{}'::jsonb,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  source_event_id uuid,
  status_reason text,
  CONSTRAINT cop_job_pkey PRIMARY KEY (id),
  CONSTRAINT cop_job_topic_id_fkey FOREIGN KEY (topic_id) REFERENCES public.cop_topic(id)
);
CREATE TABLE public.cop_nodes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  network_id text NOT NULL,
  node_id text NOT NULL,
  base_url text NOT NULL,
  cop_path text NOT NULL DEFAULT '/cop'::text,
  events_path text NOT NULL DEFAULT '/cop-events'::text,
  stream_path text NOT NULL DEFAULT '/cop-stream'::text,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT cop_nodes_pkey PRIMARY KEY (id)
);
CREATE TABLE public.cop_step (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  job_id uuid NOT NULL,
  name text NOT NULL,
  status text NOT NULL DEFAULT 'pending'::text,
  input jsonb DEFAULT '{}'::jsonb,
  output jsonb DEFAULT '{}'::jsonb,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  attempts integer DEFAULT 0,
  max_attempts integer DEFAULT 3,
  worker_id text,
  lease_expires_at timestamp with time zone,
  checkpoint jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT cop_step_pkey PRIMARY KEY (id),
  CONSTRAINT cop_step_job_id_fkey FOREIGN KEY (job_id) REFERENCES public.cop_job(id)
);
CREATE TABLE public.cop_topic (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  status text NOT NULL DEFAULT 'open'::text,
  current_version integer NOT NULL DEFAULT 1 CHECK (current_version > 0),
  title text,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT cop_topic_pkey PRIMARY KEY (id)
);
CREATE TABLE public.cortideri_items (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  post_id bigint UNIQUE,
  category_id integer,
  url text,
  list_title text,
  title text,
  content_text text,
  image_url text,
  content_html text,
  comment_count integer,
  tags ARRAY,
  image_urls ARRAY,
  scraped_at timestamp with time zone DEFAULT now(),
  source_id uuid,
  synced_at timestamp with time zone,
  CONSTRAINT cortideri_items_pkey PRIMARY KEY (id)
);
CREATE TABLE public.crawl_runs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  source_id uuid,
  started_at timestamp with time zone DEFAULT now(),
  finished_at timestamp with time zone,
  status text DEFAULT 'running'::text,
  error_message text,
  CONSTRAINT crawl_runs_pkey PRIMARY KEY (id),
  CONSTRAINT crawl_runs_source_id_fkey FOREIGN KEY (source_id) REFERENCES public.sources_web(id)
);
CREATE TABLE public.deadline_instance (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  entity_type USER-DEFINED NOT NULL,
  entity_id uuid NOT NULL,
  template_id uuid NOT NULL,
  start_date date NOT NULL,
  due_date date NOT NULL,
  status USER-DEFINED NOT NULL DEFAULT 'OUVERTE'::deadline_status,
  closed_at timestamp with time zone,
  closed_by_user_id uuid,
  closed_proof_id uuid,
  closed_reason text,
  generated_status_id uuid,
  metadata jsonb NOT NULL DEFAULT '{"schemaVersion": 1}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT deadline_instance_pkey PRIMARY KEY (id),
  CONSTRAINT deadline_instance_closed_by_user_id_fkey FOREIGN KEY (closed_by_user_id) REFERENCES public.users(id),
  CONSTRAINT deadline_instance_closed_proof_id_fkey FOREIGN KEY (closed_proof_id) REFERENCES public.proof(id),
  CONSTRAINT deadline_instance_generated_status_id_fkey FOREIGN KEY (generated_status_id) REFERENCES public.legal_status_instance(id),
  CONSTRAINT deadline_instance_template_id_fkey FOREIGN KEY (template_id) REFERENCES public.deadline_template(id)
);
CREATE TABLE public.deadline_template (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  entity_type USER-DEFINED NOT NULL,
  code text NOT NULL,
  libelle text NOT NULL,
  trigger_event USER-DEFINED NOT NULL,
  delay_days integer NOT NULL CHECK (delay_days > 0),
  delay_type USER-DEFINED NOT NULL DEFAULT 'JOURS_CALENDAIRES'::delay_type,
  base_legale text NOT NULL,
  action_attendue text NOT NULL,
  action_responsable text,
  consequence_depassement USER-DEFINED,
  consequence_description text,
  is_active boolean NOT NULL DEFAULT true,
  metadata jsonb NOT NULL DEFAULT '{"schemaVersion": 1}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT deadline_template_pkey PRIMARY KEY (id)
);
CREATE TABLE public.delegations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  delegator_id uuid NOT NULL,
  delegate_id uuid NOT NULL,
  tag_id uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  metadata jsonb NOT NULL DEFAULT '{"schemaVersion": 1}'::jsonb,
  CONSTRAINT delegations_pkey PRIMARY KEY (id),
  CONSTRAINT delegations_delegate_id_fkey FOREIGN KEY (delegate_id) REFERENCES public.users(id),
  CONSTRAINT delegations_delegator_id_fkey FOREIGN KEY (delegator_id) REFERENCES public.users(id),
  CONSTRAINT delegations_tag_id_fkey FOREIGN KEY (tag_id) REFERENCES public.tags(id)
);
CREATE TABLE public.demande_admin (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  collectivite_id uuid NOT NULL,
  acte_id uuid,
  type_demande USER-DEFINED NOT NULL,
  destinataire_org text NOT NULL,
  destinataire_contact text,
  destinataire_email text,
  date_envoi date NOT NULL CHECK (date_envoi <= (CURRENT_DATE + '1 day'::interval)),
  mode_envoi USER-DEFINED NOT NULL,
  objet text NOT NULL,
  texte_envoye text,
  status USER-DEFINED NOT NULL DEFAULT 'EN_ATTENTE'::demande_status,
  reference_interne text,
  reference_admin text,
  metadata jsonb NOT NULL DEFAULT '{"schemaVersion": 1}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  CONSTRAINT demande_admin_pkey PRIMARY KEY (id),
  CONSTRAINT demande_admin_acte_id_fkey FOREIGN KEY (acte_id) REFERENCES public.acte(id),
  CONSTRAINT demande_admin_collectivite_id_fkey FOREIGN KEY (collectivite_id) REFERENCES public.collectivite(id),
  CONSTRAINT demande_admin_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.document_sources (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  filename text NOT NULL,
  content_hash text NOT NULL UNIQUE,
  public_url text NOT NULL,
  file_size_bytes bigint,
  mime_type text,
  metadata jsonb DEFAULT '{}'::jsonb,
  first_ingested_at timestamp with time zone DEFAULT now(),
  last_ingested_at timestamp with time zone DEFAULT now(),
  ingestion_method text CHECK (ingestion_method = ANY (ARRAY['ui_upload'::text, 'cli_bulk'::text, 'cache_rebuild'::text])),
  status text DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'archived'::text, 'deleted'::text])),
  ingested_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  domain text,
  source_type text,
  external_id text,
  CONSTRAINT document_sources_pkey PRIMARY KEY (id),
  CONSTRAINT document_sources_ingested_by_fkey FOREIGN KEY (ingested_by) REFERENCES public.users(id)
);
CREATE TABLE public.federation_registry (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  instance_url text NOT NULL UNIQUE,
  instance_name text NOT NULL,
  instance_type text NOT NULL DEFAULT 'commune'::text CHECK (instance_type = ANY (ARRAY['commune'::text, 'region'::text, 'national'::text, 'custom'::text])),
  commune_name text,
  commune_insee text,
  region_name text,
  region_code text,
  api_endpoint text,
  api_key_hash text,
  is_hub boolean NOT NULL DEFAULT false,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'active'::text, 'suspended'::text, 'revoked'::text])),
  verified_at timestamp with time zone,
  last_seen_at timestamp with time zone,
  federation_config jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT federation_registry_pkey PRIMARY KEY (id)
);
CREATE TABLE public.feeds (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  url text NOT NULL UNIQUE,
  title text,
  type text NOT NULL CHECK (type = ANY (ARRAY['jsonfeed'::text, 'rss'::text, 'atom'::text, 'internal'::text])),
  category text,
  is_internal boolean NOT NULL DEFAULT false,
  is_indexed_by_ai boolean NOT NULL DEFAULT false,
  etag text,
  last_modified text,
  last_fetched_at timestamp with time zone,
  last_status text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  metadata jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT feeds_pkey PRIMARY KEY (id)
);
CREATE TABLE public.git_sync_log (
  page_id uuid NOT NULL,
  last_sync_date date NOT NULL,
  commit_sha text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT git_sync_log_pkey PRIMARY KEY (page_id, last_sync_date),
  CONSTRAINT git_sync_log_page_id_fkey FOREIGN KEY (page_id) REFERENCES public.wiki_pages(id)
);
CREATE TABLE public.group_members (
  group_id uuid NOT NULL,
  user_id uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  metadata jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT group_members_pkey PRIMARY KEY (group_id, user_id),
  CONSTRAINT group_members_group_id_fkey FOREIGN KEY (group_id) REFERENCES public.groups(id),
  CONSTRAINT group_members_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.groups (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name text NOT NULL,
  description text,
  created_by uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  metadata jsonb NOT NULL DEFAULT '{"schemaVersion": 1}'::jsonb,
  CONSTRAINT groups_pkey PRIMARY KEY (id),
  CONSTRAINT groups_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.inseme_messages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  room_id text NOT NULL,
  user_id uuid,
  name text NOT NULL,
  message text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  type text DEFAULT 'chat'::text,
  metadata jsonb DEFAULT '{}'::jsonb,
  embedding USER-DEFINED,
  CONSTRAINT inseme_messages_pkey PRIMARY KEY (id),
  CONSTRAINT inseme_messages_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.inseme_rooms (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  slug text NOT NULL UNIQUE,
  owner_id uuid,
  name text NOT NULL,
  settings jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT inseme_rooms_pkey PRIMARY KEY (id),
  CONSTRAINT inseme_rooms_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES auth.users(id)
);
CREATE TABLE public.instance_config (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  key text NOT NULL UNIQUE,
  value text,
  value_json jsonb,
  category text NOT NULL DEFAULT 'general'::text,
  description text,
  is_secret boolean DEFAULT false,
  is_public boolean DEFAULT false,
  version integer DEFAULT 1,
  previous_value text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  updated_by uuid,
  CONSTRAINT instance_config_pkey PRIMARY KEY (id),
  CONSTRAINT instance_config_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.users(id)
);
CREATE TABLE public.instance_registry (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  subdomain text NOT NULL UNIQUE,
  display_name text NOT NULL,
  description text,
  supabase_url text NOT NULL,
  supabase_anon_key text NOT NULL,
  status text NOT NULL DEFAULT 'active'::text CHECK (status = ANY (ARRAY['pending'::text, 'active'::text, 'suspended'::text, 'archived'::text])),
  metadata jsonb DEFAULT '{}'::jsonb,
  instance_type text DEFAULT 'municipality'::text CHECK (instance_type = ANY (ARRAY['municipality'::text, 'epci'::text, 'region'::text, 'national'::text, 'association'::text, 'university'::text, 'cooperative'::text, 'cse'::text, 'copropriete'::text, 'other'::text])),
  is_hub boolean DEFAULT false,
  hub_type text,
  parent_hub_id uuid,
  logo_url text,
  primary_color text DEFAULT '#B35A4A'::text,
  custom_domain text,
  admin_email text,
  contact_email text,
  stats jsonb DEFAULT '{}'::jsonb,
  schema_version text,
  schema_updated_at timestamp with time zone,
  migrations_count integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  activated_at timestamp with time zone,
  suspended_at timestamp with time zone,
  CONSTRAINT instance_registry_pkey PRIMARY KEY (id),
  CONSTRAINT instance_registry_parent_hub_id_fkey FOREIGN KEY (parent_hub_id) REFERENCES public.instance_registry(id)
);
CREATE TABLE public.jobs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  owner uuid,
  type text NOT NULL,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'running'::text, 'completed'::text, 'failed'::text, 'cancelled'::text])),
  progress integer NOT NULL DEFAULT 0 CHECK (progress >= 0 AND progress <= 100),
  message text,
  payload jsonb DEFAULT '{}'::jsonb,
  result jsonb,
  error_details jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  started_at timestamp with time zone,
  completed_at timestamp with time zone,
  CONSTRAINT jobs_pkey PRIMARY KEY (id),
  CONSTRAINT jobs_owner_fkey FOREIGN KEY (owner) REFERENCES public.users(id)
);
CREATE TABLE public.knowledge_chunks (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  source_id uuid,
  text text NOT NULL,
  text_hash text NOT NULL,
  embedding USER-DEFINED,
  type text NOT NULL CHECK (type = ANY (ARRAY['fact'::text, 'allegation'::text, 'opinion'::text])),
  status text NOT NULL DEFAULT 'under_review'::text CHECK (status = ANY (ARRAY['under_review'::text, 'confirmed'::text, 'refuted'::text, 'obsolete'::text])),
  source_type text NOT NULL,
  domain text NOT NULL,
  territory text NOT NULL DEFAULT 'Corte'::text,
  info_date date,
  layer text NOT NULL DEFAULT 'hot'::text CHECK (layer = ANY (ARRAY['hot'::text, 'summary'::text, 'archive'::text])),
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT knowledge_chunks_pkey PRIMARY KEY (id),
  CONSTRAINT knowledge_chunks_source_id_fkey FOREIGN KEY (source_id) REFERENCES public.document_sources(id)
);
CREATE TABLE public.lead_interactions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  lead_id uuid NOT NULL,
  interaction_type text NOT NULL CHECK (interaction_type = ANY (ARRAY['email_sent'::text, 'email_opened'::text, 'email_clicked'::text, 'call'::text, 'meeting'::text, 'demo'::text, 'onboarding'::text, 'support'::text, 'note'::text])),
  subject text,
  content text,
  outcome text,
  performed_by uuid,
  performed_at timestamp with time zone DEFAULT now(),
  metadata jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT lead_interactions_pkey PRIMARY KEY (id),
  CONSTRAINT lead_interactions_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES public.transparency_leads(id),
  CONSTRAINT lead_interactions_performed_by_fkey FOREIGN KEY (performed_by) REFERENCES auth.users(id)
);
CREATE TABLE public.legal_status_instance (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  entity_type USER-DEFINED NOT NULL,
  entity_id uuid NOT NULL,
  status_code USER-DEFINED NOT NULL,
  date_debut date NOT NULL,
  date_fin date,
  justification text,
  base_legale text,
  proof_id uuid,
  created_by_user_id uuid,
  created_by_actor_type USER-DEFINED NOT NULL DEFAULT 'HUMAIN'::civic_actor_type,
  metadata jsonb NOT NULL DEFAULT '{"schemaVersion": 1}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT legal_status_instance_pkey PRIMARY KEY (id),
  CONSTRAINT legal_status_instance_created_by_user_id_fkey FOREIGN KEY (created_by_user_id) REFERENCES public.users(id),
  CONSTRAINT legal_status_instance_proof_id_fkey FOREIGN KEY (proof_id) REFERENCES public.proof(id)
);
CREATE TABLE public.legal_status_registry (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  entity_type USER-DEFINED NOT NULL,
  status_code USER-DEFINED NOT NULL,
  libelle text NOT NULL,
  base_legale text,
  effets_juridiques text,
  delay_trigger boolean NOT NULL DEFAULT false,
  metadata jsonb NOT NULL DEFAULT '{"schemaVersion": 1}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT legal_status_registry_pkey PRIMARY KEY (id)
);
CREATE TABLE public.municipal_documents (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  source_id uuid,
  source_doc_id text,
  source_url text NOT NULL,
  type text NOT NULL,
  title text NOT NULL,
  summary text,
  content_html text,
  published_at timestamp with time zone,
  attachment_url text,
  attachment_content_type text,
  raw_document_id uuid,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT municipal_documents_pkey PRIMARY KEY (id),
  CONSTRAINT municipal_documents_raw_document_id_fkey FOREIGN KEY (raw_document_id) REFERENCES public.municipal_raw_documents(id),
  CONSTRAINT municipal_documents_source_id_fkey FOREIGN KEY (source_id) REFERENCES public.sources_web(id)
);
CREATE TABLE public.municipal_poi (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  source_id uuid,
  source_poi_id text,
  raw_document_id uuid,
  name text NOT NULL,
  category text,
  subcategory text,
  description text,
  latitude double precision,
  longitude double precision,
  geom USER-DEFINED DEFAULT 
CASE
    WHEN ((latitude IS NOT NULL) AND (longitude IS NOT NULL)) THEN st_setsrid(st_makepoint(longitude, latitude), 4326)
    ELSE NULL::geometry
END,
  external_url text,
  internal_page_url text,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT municipal_poi_pkey PRIMARY KEY (id),
  CONSTRAINT municipal_poi_raw_document_id_fkey FOREIGN KEY (raw_document_id) REFERENCES public.municipal_raw_documents(id),
  CONSTRAINT municipal_poi_source_id_fkey FOREIGN KEY (source_id) REFERENCES public.sources_web(id)
);
CREATE TABLE public.municipal_raw_documents (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  source_id uuid,
  crawl_run_id uuid,
  url text NOT NULL,
  content_type text,
  http_status integer,
  retrieved_at timestamp with time zone DEFAULT now(),
  etag text,
  last_modified text,
  body bytea,
  body_text text,
  hash_content text,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT municipal_raw_documents_pkey PRIMARY KEY (id),
  CONSTRAINT municipal_raw_documents_crawl_run_id_fkey FOREIGN KEY (crawl_run_id) REFERENCES public.crawl_runs(id),
  CONSTRAINT municipal_raw_documents_source_id_fkey FOREIGN KEY (source_id) REFERENCES public.sources_web(id)
);
CREATE TABLE public.municipal_transparency (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  commune_name text NOT NULL,
  insee_code text,
  population integer CHECK (population >= 0),
  agenda_mentions_location boolean NOT NULL DEFAULT false,
  livestreamed boolean NOT NULL DEFAULT false,
  minutes_published_under_week boolean NOT NULL DEFAULT false,
  deliberations_open_data boolean NOT NULL DEFAULT false,
  annual_calendar_published boolean NOT NULL DEFAULT false,
  public_can_speak boolean NOT NULL DEFAULT false,
  contact_email text,
  submitted_by text,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT municipal_transparency_pkey PRIMARY KEY (id)
);
CREATE TABLE public.outgoing_action (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  collectivite_id uuid NOT NULL,
  acte_id uuid,
  demande_admin_id uuid,
  action_type USER-DEFINED NOT NULL,
  status USER-DEFINED NOT NULL DEFAULT 'PENDING'::outgoing_action_status,
  destinataire_nom text,
  destinataire_email text,
  destinataire_adresse text,
  sujet text NOT NULL,
  corps text NOT NULL,
  pieces_jointes jsonb DEFAULT '[]'::jsonb,
  priority integer DEFAULT 5,
  date_butoir date,
  motif text,
  created_by uuid NOT NULL,
  validated_by uuid,
  validated_at timestamp with time zone,
  validation_note text,
  sent_at timestamp with time zone,
  sent_by uuid,
  send_method text,
  send_reference text,
  confirmed_at timestamp with time zone,
  confirmation_proof_id uuid,
  failure_reason text,
  retry_count integer DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT outgoing_action_pkey PRIMARY KEY (id),
  CONSTRAINT outgoing_action_acte_id_fkey FOREIGN KEY (acte_id) REFERENCES public.acte(id),
  CONSTRAINT outgoing_action_collectivite_id_fkey FOREIGN KEY (collectivite_id) REFERENCES public.collectivite(id),
  CONSTRAINT outgoing_action_confirmation_proof_id_fkey FOREIGN KEY (confirmation_proof_id) REFERENCES public.proof(id),
  CONSTRAINT outgoing_action_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id),
  CONSTRAINT outgoing_action_demande_admin_id_fkey FOREIGN KEY (demande_admin_id) REFERENCES public.demande_admin(id),
  CONSTRAINT outgoing_action_sent_by_fkey FOREIGN KEY (sent_by) REFERENCES auth.users(id),
  CONSTRAINT outgoing_action_validated_by_fkey FOREIGN KEY (validated_by) REFERENCES auth.users(id)
);
CREATE TABLE public.posts (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  author_id uuid NOT NULL,
  content text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  metadata jsonb NOT NULL DEFAULT '{"schemaVersion": 1}'::jsonb,
  CONSTRAINT posts_pkey PRIMARY KEY (id),
  CONSTRAINT posts_author_id_fkey FOREIGN KEY (author_id) REFERENCES public.users(id)
);
CREATE TABLE public.proof (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  type USER-DEFINED NOT NULL,
  source_org USER-DEFINED NOT NULL,
  date_emission date,
  date_reception date,
  hash_sha256 text NOT NULL CHECK (length(hash_sha256) = 64),
  storage_url text NOT NULL,
  original_filename text,
  file_size_bytes bigint,
  mime_type text,
  probative_force USER-DEFINED NOT NULL DEFAULT 'FAIBLE'::probative_force,
  verified_by_human boolean NOT NULL DEFAULT false,
  verified_by_user_id uuid,
  verified_at timestamp with time zone,
  verification_notes text,
  metadata jsonb NOT NULL DEFAULT '{"schemaVersion": 1}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  CONSTRAINT proof_pkey PRIMARY KEY (id),
  CONSTRAINT proof_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT proof_verified_by_user_id_fkey FOREIGN KEY (verified_by_user_id) REFERENCES public.users(id)
);
CREATE TABLE public.proof_link (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  proof_id uuid NOT NULL,
  entity_type USER-DEFINED NOT NULL,
  entity_id uuid NOT NULL,
  role USER-DEFINED NOT NULL DEFAULT 'PIECE_PRINCIPALE'::proof_role,
  piece_number integer,
  metadata jsonb NOT NULL DEFAULT '{"schemaVersion": 1}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT proof_link_pkey PRIMARY KEY (id),
  CONSTRAINT proof_link_proof_id_fkey FOREIGN KEY (proof_id) REFERENCES public.proof(id)
);
CREATE TABLE public.proposition_tags (
  proposition_id uuid NOT NULL,
  tag_id uuid NOT NULL,
  CONSTRAINT proposition_tags_pkey PRIMARY KEY (proposition_id, tag_id),
  CONSTRAINT proposition_tags_proposition_id_fkey FOREIGN KEY (proposition_id) REFERENCES public.propositions(id),
  CONSTRAINT proposition_tags_tag_id_fkey FOREIGN KEY (tag_id) REFERENCES public.tags(id)
);
CREATE TABLE public.propositions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title text NOT NULL,
  description text NOT NULL,
  author_id uuid,
  status text DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'closed'::text, 'draft'::text])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  metadata jsonb NOT NULL DEFAULT '{"schemaVersion": 1}'::jsonb,
  CONSTRAINT propositions_pkey PRIMARY KEY (id),
  CONSTRAINT propositions_author_id_fkey FOREIGN KEY (author_id) REFERENCES public.users(id)
);
CREATE TABLE public.publication_citoyenne (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  collectivite_id uuid NOT NULL,
  acte_id uuid,
  demande_admin_id uuid,
  publication_type USER-DEFINED NOT NULL,
  status USER-DEFINED NOT NULL DEFAULT 'DRAFT'::publication_status,
  titre text NOT NULL,
  resume text,
  contenu text NOT NULL,
  tags ARRAY DEFAULT '{}'::text[],
  author_id uuid NOT NULL,
  author_pseudonym text,
  is_anonymous boolean DEFAULT false,
  moderated_by uuid,
  moderated_at timestamp with time zone,
  moderation_note text,
  rejection_reason text,
  views_count integer DEFAULT 0,
  likes_count integer DEFAULT 0,
  shares_count integer DEFAULT 0,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  published_at timestamp with time zone,
  CONSTRAINT publication_citoyenne_pkey PRIMARY KEY (id),
  CONSTRAINT publication_citoyenne_acte_id_fkey FOREIGN KEY (acte_id) REFERENCES public.acte(id),
  CONSTRAINT publication_citoyenne_author_id_fkey FOREIGN KEY (author_id) REFERENCES auth.users(id),
  CONSTRAINT publication_citoyenne_collectivite_id_fkey FOREIGN KEY (collectivite_id) REFERENCES public.collectivite(id),
  CONSTRAINT publication_citoyenne_demande_admin_id_fkey FOREIGN KEY (demande_admin_id) REFERENCES public.demande_admin(id),
  CONSTRAINT publication_citoyenne_moderated_by_fkey FOREIGN KEY (moderated_by) REFERENCES auth.users(id)
);
CREATE TABLE public.reactions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  target_type text NOT NULL,
  target_id uuid NOT NULL,
  emoji text NOT NULL,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT reactions_pkey PRIMARY KEY (id),
  CONSTRAINT reactions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.recours (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  collectivite_id uuid NOT NULL,
  type USER-DEFINED NOT NULL,
  demande_id uuid,
  acte_id uuid,
  date_envoi date,
  date_reception_ack date,
  date_instruction date,
  date_audience date,
  date_decision date,
  destinataire_org text NOT NULL,
  destinataire_adresse text,
  numero_dossier text,
  status USER-DEFINED NOT NULL DEFAULT 'EN_PREPARATION'::recours_status,
  issue USER-DEFINED,
  resume_objet text,
  moyens text,
  conclusions text,
  proof_id_envoi uuid,
  proof_id_decision uuid,
  metadata jsonb NOT NULL DEFAULT '{"schemaVersion": 1}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  CONSTRAINT recours_pkey PRIMARY KEY (id),
  CONSTRAINT recours_acte_id_fkey FOREIGN KEY (acte_id) REFERENCES public.acte(id),
  CONSTRAINT recours_collectivite_id_fkey FOREIGN KEY (collectivite_id) REFERENCES public.collectivite(id),
  CONSTRAINT recours_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT recours_demande_id_fkey FOREIGN KEY (demande_id) REFERENCES public.demande_admin(id),
  CONSTRAINT recours_proof_id_decision_fkey FOREIGN KEY (proof_id_decision) REFERENCES public.proof(id),
  CONSTRAINT recours_proof_id_envoi_fkey FOREIGN KEY (proof_id_envoi) REFERENCES public.proof(id)
);
CREATE TABLE public.reponse_admin (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  demande_id uuid NOT NULL,
  date_reception date NOT NULL,
  type_reponse USER-DEFINED NOT NULL,
  resume text,
  proof_id uuid,
  metadata jsonb NOT NULL DEFAULT '{"schemaVersion": 1}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  CONSTRAINT reponse_admin_pkey PRIMARY KEY (id),
  CONSTRAINT reponse_admin_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT reponse_admin_demande_id_fkey FOREIGN KEY (demande_id) REFERENCES public.demande_admin(id),
  CONSTRAINT reponse_admin_proof_id_fkey FOREIGN KEY (proof_id) REFERENCES public.proof(id)
);
CREATE TABLE public.responsibility_log (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  actor_id uuid NOT NULL,
  actor_role text NOT NULL,
  responsibility_type USER-DEFINED NOT NULL,
  action_description text NOT NULL,
  entity_type text NOT NULL,
  entity_id uuid NOT NULL,
  collectivite_id uuid,
  before_state jsonb,
  after_state jsonb,
  reason text,
  ip_address inet,
  user_agent text,
  checksum text,
  logged_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT responsibility_log_pkey PRIMARY KEY (id),
  CONSTRAINT responsibility_log_actor_id_fkey FOREIGN KEY (actor_id) REFERENCES auth.users(id),
  CONSTRAINT responsibility_log_collectivite_id_fkey FOREIGN KEY (collectivite_id) REFERENCES public.collectivite(id)
);
CREATE TABLE public.saas_config (
  key text NOT NULL,
  value text,
  is_secret boolean DEFAULT false,
  description text,
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT saas_config_pkey PRIMARY KEY (key)
);
CREATE TABLE public.saas_instances (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  commune_name text NOT NULL,
  commune_insee text UNIQUE,
  region_code text,
  epci_siren text,
  is_hub boolean DEFAULT false,
  hub_type text CHECK (hub_type = ANY (ARRAY['commune'::text, 'epci'::text, 'region'::text, 'national'::text])),
  instance_url text,
  supabase_project_id text,
  supabase_url text,
  netlify_site_id text,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'provisioning'::text, 'active'::text, 'suspended'::text, 'error'::text])),
  admin_email text NOT NULL,
  admin_user_id uuid,
  storage_used_bytes bigint DEFAULT 0,
  api_calls_month integer DEFAULT 0,
  users_count integer DEFAULT 0,
  last_activity_at timestamp with time zone,
  metadata jsonb DEFAULT '{}'::jsonb,
  provisioning_log jsonb DEFAULT '[]'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT saas_instances_pkey PRIMARY KEY (id)
);
CREATE TABLE public.saas_provisioning_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  instance_id uuid NOT NULL,
  step text NOT NULL,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'running'::text, 'success'::text, 'error'::text, 'skipped'::text])),
  started_at timestamp with time zone,
  completed_at timestamp with time zone,
  details jsonb DEFAULT '{}'::jsonb,
  error_message text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT saas_provisioning_logs_pkey PRIMARY KEY (id),
  CONSTRAINT saas_provisioning_logs_instance_id_fkey FOREIGN KEY (instance_id) REFERENCES public.saas_instances(id)
);
CREATE TABLE public.schema_migrations (
  id integer NOT NULL DEFAULT nextval('schema_migrations_id_seq'::regclass),
  version character varying NOT NULL UNIQUE,
  name character varying NOT NULL,
  applied_at timestamp with time zone DEFAULT now(),
  checksum character varying,
  execution_time_ms integer,
  applied_by character varying DEFAULT 'system'::character varying,
  CONSTRAINT schema_migrations_pkey PRIMARY KEY (id)
);
CREATE TABLE public.schema_version (
  id integer NOT NULL DEFAULT 1 CHECK (id = 1),
  current_version character varying NOT NULL,
  updated_at timestamp with time zone DEFAULT now(),
  instance_id character varying,
  CONSTRAINT schema_version_pkey PRIMARY KEY (id)
);
CREATE TABLE public.sources_web (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  label text NOT NULL,
  base_url text NOT NULL,
  description text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT sources_web_pkey PRIMARY KEY (id)
);
CREATE TABLE public.spatial_ref_sys (
  srid integer NOT NULL CHECK (srid > 0 AND srid <= 998999),
  auth_name character varying,
  auth_srid integer,
  srtext character varying,
  proj4text character varying,
  CONSTRAINT spatial_ref_sys_pkey PRIMARY KEY (srid)
);
CREATE TABLE public.tags (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL UNIQUE,
  description text DEFAULT ''::text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  metadata jsonb NOT NULL DEFAULT '{"schemaVersion": 1}'::jsonb,
  CONSTRAINT tags_pkey PRIMARY KEY (id)
);
CREATE TABLE public.teletransmission (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  acte_id uuid NOT NULL UNIQUE,
  date_declared date,
  heure_declared time without time zone,
  date_confirmed date,
  heure_confirmed time without time zone,
  proof_id_ar_ctes uuid,
  numero_ctes text,
  statut_technique USER-DEFINED NOT NULL DEFAULT 'INCONNU'::teletransmission_status,
  motif_rejet text,
  metadata jsonb NOT NULL DEFAULT '{"schemaVersion": 1}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT teletransmission_pkey PRIMARY KEY (id),
  CONSTRAINT teletransmission_acte_id_fkey FOREIGN KEY (acte_id) REFERENCES public.acte(id),
  CONSTRAINT teletransmission_proof_id_ar_ctes_fkey FOREIGN KEY (proof_id_ar_ctes) REFERENCES public.proof(id)
);
CREATE TABLE public.transparency_leads (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  lead_type text NOT NULL CHECK (lead_type = ANY (ARRAY['liste_electorale'::text, 'maire_elu'::text, 'collectif_citoyen'::text, 'citoyen_engage'::text])),
  maturity_level integer NOT NULL DEFAULT 1 CHECK (maturity_level >= 1 AND maturity_level <= 4),
  name text NOT NULL,
  email text NOT NULL,
  phone text,
  commune_name text NOT NULL,
  commune_insee text,
  organization_name text,
  message text,
  accepted_charter boolean DEFAULT false,
  accepted_contact boolean DEFAULT true,
  source text DEFAULT 'landing_page'::text,
  referrer_url text,
  utm_source text,
  utm_medium text,
  utm_campaign text,
  metadata jsonb DEFAULT '{}'::jsonb,
  status text DEFAULT 'new'::text CHECK (status = ANY (ARRAY['new'::text, 'contacted'::text, 'qualified'::text, 'onboarding'::text, 'active'::text, 'churned'::text, 'duplicate'::text])),
  notes text,
  assigned_to uuid,
  instance_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  contacted_at timestamp with time zone,
  converted_at timestamp with time zone,
  CONSTRAINT transparency_leads_pkey PRIMARY KEY (id),
  CONSTRAINT transparency_leads_assigned_to_fkey FOREIGN KEY (assigned_to) REFERENCES auth.users(id),
  CONSTRAINT transparency_leads_instance_id_fkey FOREIGN KEY (instance_id) REFERENCES public.saas_instances(id)
);
CREATE TABLE public.user_consents (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  consent_type text NOT NULL CHECK (consent_type = ANY (ARRAY['rgpd_general'::text, 'public_profile'::text, 'ia_analysis'::text, 'newsletter'::text, 'notification_email'::text])),
  granted boolean NOT NULL DEFAULT false,
  consent_version text NOT NULL DEFAULT '1.0'::text,
  consent_text_hash text,
  source text NOT NULL CHECK (source = ANY (ARRAY['web'::text, 'mobile'::text, 'api'::text, 'admin'::text])),
  ip_hash text,
  user_agent_category text,
  granted_at timestamp with time zone,
  revoked_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT user_consents_pkey PRIMARY KEY (id),
  CONSTRAINT user_consents_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.user_feed_subscriptions (
  user_id uuid NOT NULL,
  feed_id uuid NOT NULL,
  category text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT user_feed_subscriptions_pkey PRIMARY KEY (user_id, feed_id),
  CONSTRAINT user_feed_subscriptions_feed_id_fkey FOREIGN KEY (feed_id) REFERENCES public.feeds(id),
  CONSTRAINT user_feed_subscriptions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.users (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  display_name text NOT NULL DEFAULT ''::text,
  created_at timestamp with time zone DEFAULT now(),
  neighborhood text,
  interests text,
  rgpd_consent_accepted boolean DEFAULT false,
  rgpd_consent_date timestamp with time zone,
  updated_at timestamp with time zone DEFAULT now(),
  metadata jsonb NOT NULL DEFAULT '{"schemaVersion": 1}'::jsonb,
  role text NOT NULL DEFAULT 'user'::text CHECK (role = ANY (ARRAY['user'::text, 'moderator'::text, 'admin'::text, 'ai'::text, 'represented'::text])),
  public_profile boolean NOT NULL DEFAULT true,
  avatar_url text,
  CONSTRAINT users_pkey PRIMARY KEY (id)
);
CREATE TABLE public.verification_queue (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  proof_id uuid NOT NULL,
  status text NOT NULL DEFAULT 'PENDING'::text CHECK (status = ANY (ARRAY['PENDING'::text, 'IN_PROGRESS'::text, 'VERIFIED'::text, 'REJECTED'::text])),
  priority integer DEFAULT 5,
  assigned_to uuid,
  assigned_at timestamp with time zone,
  verified_by uuid,
  verified_at timestamp with time zone,
  verification_note text,
  rejection_reason text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT verification_queue_pkey PRIMARY KEY (id),
  CONSTRAINT verification_queue_assigned_to_fkey FOREIGN KEY (assigned_to) REFERENCES auth.users(id),
  CONSTRAINT verification_queue_proof_id_fkey FOREIGN KEY (proof_id) REFERENCES public.proof(id),
  CONSTRAINT verification_queue_verified_by_fkey FOREIGN KEY (verified_by) REFERENCES auth.users(id)
);
CREATE TABLE public.votes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  proposition_id uuid NOT NULL,
  vote_value text CHECK (vote_value = ANY (ARRAY['approve'::text, 'disapprove'::text, 'neutral'::text, 'false_choice'::text])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  metadata jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT votes_pkey PRIMARY KEY (id),
  CONSTRAINT votes_proposition_id_fkey FOREIGN KEY (proposition_id) REFERENCES public.propositions(id),
  CONSTRAINT votes_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.wiki_pages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  slug text NOT NULL UNIQUE,
  title text NOT NULL,
  content text NOT NULL,
  author_id uuid,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  summary text,
  metadata jsonb NOT NULL DEFAULT '{"schemaVersion": 1}'::jsonb,
  fts_tokens tsvector,
  embedding USER-DEFINED,
  CONSTRAINT wiki_pages_pkey PRIMARY KEY (id),
  CONSTRAINT wiki_pages_author_id_fkey FOREIGN KEY (author_id) REFERENCES public.users(id)
);
